### ISSUE TITLE
Make spritesheet

### ISSUE THREAD

**Issue by evinstk** [TheGovernorsJunk/CaulsCastle#1]
Make spritesheet of simple, animated character to get used to the format of spritesheets.

**Comment by evinstk** [comment]
![image](https://cloud.githubusercontent.com/assets/4632908/11201350/04c4a93a-8ca3-11e5-9324-ee5b05735015.png)

**Comment by evinstk** [comment]
https://ci.appveyor.com/project/evinstk/metroidclone/build/artifacts

**Comment by milmd90** [comment]
I am learning how to use Tiled and it seems that to use this sprite sheet, I have to know the tile size, spacing and margin. Currently, I am creating a new tileset over and over from the same image, and adjusting the parameters to get something that looks ok. Is there a better way to do this if you do not know the image size? If not, what is the correct info for this sheet? What grid size are we going to use for our game?

**Comment by evinstk** [comment]
If you're using the above image, I grabbed this Samus sheet from a Google image search. Typically, when you get a sprite sheet it'll come packaged with info on tile dimensions and spacings. I didn't check for this one; I was just showing Ryan an example of a sprite sheet.

Good sprite sheet samples can be found on [Kenney.nl](http://kenney.nl). They usually come packaged with a TXT file that tells you the relevant dimensions so you don't have to guess and check.

**Comment by evinstk** [comment]
As for our tile size, probably 32x32 or 16x16, but we'll see what Ryan comes up with first.

**Comment by GlasselRat** [comment]
They made me post it oddly, but here is a basic idle animation.  Order is {0, 1, 4, 3, 0, 2} repeating.

And since I had nothing to work off of for these I officially present my story idea:   Nana Goes Nanners.  They took away Bingo Night, she took away their lives.    @TheGovernorsJunk/writers 

![metroid clone sprite idle 0 fw](https://cloud.githubusercontent.com/assets/15863958/11258975/96c3704c-8e23-11e5-924d-33eae982a226.png)
![metroid clone sprite idle 1 fw](https://cloud.githubusercontent.com/assets/15863958/11258976/96c60d34-8e23-11e5-9c8b-9e723940c244.png)
![metroid clone sprite idle 2 fw](https://cloud.githubusercontent.com/assets/15863958/11258977/96c7717e-8e23-11e5-9885-45eaf96f788b.png)
![metroid clone sprite idle 3 fw](https://cloud.githubusercontent.com/assets/15863958/11258978/96c8daaa-8e23-11e5-8358-87413583326b.png)
![metroid clone sprite idle 4 fw](https://cloud.githubusercontent.com/assets/15863958/11258979/96ca0772-8e23-11e5-968f-3e180f8470ba.png)

**Comment by evinstk** [comment]
Oh hell yes, Ryan. I'll get to work on this right away. Do you have an idea of how long you want each frame to last?

**Comment by evinstk** [comment]
![nana](https://cloud.githubusercontent.com/assets/4632908/11260391/61f3f67c-8e30-11e5-9cf3-5db7bb699826.png)
I've made a combined Nana spritesheet. Having it one image is easier on the engine.

Integrating it into the code now. You should have a demo of her moving around in a couple days :smile:.

**Comment by GlasselRat** [comment]
Timing I'm thinking maybe 2 seconds per frame, but I'm considering making another set of idle animations with the shoulders and head moving like Nana is breathing.  Then the order would have each of the regular frames twice with a shrugging one between the duplicate frames for like half a second.  So 1 second of frame 0, .5 second of frame 0 shrug, then 1 second of frame 0 again.  I think the shrug would provide a bit more of an obvious movement for the idle than just the head and gun shifts.  Currently each frame is 300 x 300 pixels with 72 pixels per inch resolution, but I imagine we would shrink them down for the game.  Having a bigger motion would help with a smaller sprite.

**Comment by evinstk** [comment]
@GlasselRat, FYI, "opening" an issue in GitHub means that it is currently unresolved. If you just want to look at the comments or post a new one, just click on the issue link. I considered this issue "closed" since you uploaded the images and I integrated them into the repository. Just want to make sure we're clear on the usage.

Thanks for the animation info. I'll work on that soon.

**Comment by GlasselRat** [comment]
Ah.  Well... It's good to learn something new everyday.
