### ISSUE TITLE
Universe 

### ISSUE THREAD

**Issue by TheRagingRabbit** [TheGovernorsJunk/CaulsCastle#8]
Alright @TheGovernorsJunk/writers what kind of universe do we want?

**Comment by RinTinRin** [comment]
A few things pop to mind. For one, Metroid and Castlevania are actually really similar in gameplay, just different skins. Ooh, aliens/monsters! Hey, what's this weird ship beam/castle tower? Let me wander back to this when I find a new missile/whip. And after @evinstk comment that we could skin it as Zelda, sky's the limit.

Let's just throw things out: multiverse a la Chrono Trigger or a Link to the Past, wherein You might visit the same place over different times. Oh, this wall blocking the path has crumbled, but the treasure has already been taken? Either find a time travel point on the other side of the wall to go back and take the treasure, or bring back something from the future to knock the wall down, so it turns out You're also the one who broke the wall. You've been going back and forth to collect the MacGuffins that will save the future. If You collect these items from the past, before the Evil Overlord (EO) destroys them, then You can save the future that is your present. M. Night Shyamalan plot twist: the EO planted the rumor that he destroyed the items to make himself seem more powerful. It turns out, it was You taking the items all along--they had never been destroyed in the first place. Now You have a choice: go back to the past to stop the EO's reign from ever happening, but the future--including You and everyone You loved--will not exist (and some plot fairy spirit blah ensures that this doesn't cause a paradox), or destroy the EO in the future to save Your home and loved ones, while knowing that it was your fault in the first place. And, because seriously, most games that deal with this type of time travel totally cop out and give you a way to resolve everything happily for all eras, no. Nope. Even though the time break could be as small as a couple of decades, You definitely won't exist anymore if You save the past, but the only way to continue in Your original timeline is to make sure the past suffers. There could be a third option for You to try to make everything right, even after being warned away from that option in-game. I would want that option to end badly, the Evil Overlord still takes over the past, and he controls the present, and he kicks a puppy, because I like it when there are actual consequences for story choice. Because dammit, the player is almost always rewarded for picking the noble self-sacrificing and/or one in a million shot option. Not this time. (Although, a "reward" for picking this and getting the worst Downer Ending would open a New Game + option where everything gets harder.)

Or: fantasy universe, probably medieval, where your character is trapped in a castle. Let's go Beauty and the Beast, except you're both. You have a human mode and a monster mode (and maybe that monster is a spinning Samus ball, idk). Human mode uses items. Monster hulk smash. I'd rather see the main character as some poor kitchen worker than the heir of the castle, but whatevs. Access to other parts of the castle also wakes up characters, and as the Beauty-Beast, you're trying to end the curse on everyone and get their humanity back. The power of true love is friendship, I guess. M. Night Shyamalan twist: because I'm fond of the "hero" majorly fucking up, it turns out the curse placed on the castle was actually an evil ritual gone wrong. Maybe the queen of the castle is secretly a demon or something, and accidentally made everyone (including her) fall asleep instead of making herself immortal. Or something. Who cares! Final magic boss fight with some stained glass pixel art ballroom background go!

Or: there is a library. Let's just steal the plot from Page Master and explore all sorts of universes by entering different books, except that you can take key items with you between books/genres. So, you need the grappling hook in the space station to get into the air vents, but then you find the space suit that lets you breathe underwater with mermaids. You collect a pearl of power from mermaids and summon a tidal wave to put out a fire in a burning apartment building with lots of platform-friendly fire escapes. And for extra fun, you can enter the books in any order. Except that that would be really taxing on the scripters, because that's a whole lot of art and mechanics, and that's totally why most games don't let the writers run wild. _completely innocent smile_

Or: all of these ideas suck, but, hey, I threw things out there, so thoughts?

**Comment by evinstk** [comment]
I'll try to refrain from supporting any particular direction since that's y'all's domain (though I like all these ideas&mdash;thanks for the contribution, @RinTinRin). Just want to mention: Don't feel constrained to create a universe for which there is a one-to-one matchup of Metroid items to our items. Our hero's arsenal might be totally unlike Samus's, beyond a superficial reskinning.

Hmm, perhaps I should have dubbed this project "Metroid Descendant" rather than "clone." Oh well.

**Comment by evinstk** [comment]
> Except that that would be really taxing on the scripters, because that's a whole lot of art and mechanics, and that's totally why most games don't let the writers run wild. _completely innocent smile_

Indeed :wink:. Probably best saved for a second or third project. The scripting component of this project is... shall we say, experimental. Lots to iron out still.

**Comment by RinTinRin** [comment]
Yep, I knew the third one was way too hard to start, but it was fun to word vomit. I think the first two have merit for working with a basic design. I was thinking my first proposal works well if it's not a long time between the Past and Future eras. The later era just gets gray tones or sepia and a few objects removed or replaced with an aged skin. (Young maiden becomes old grandma sprite, new building has cracks added to walls, or all the same but a part crumbled off.) 

Or a scenario like my second idea, being contained to one large building, like a castle(vania) where a "wing" logically translates into any kind of map you want, really, including the one @adian91 proposed. Or if we go Metroid Descendant in spaaaaaaace, then a space station can easily have parts that would be shut off from each other to create levels, same principle.

The ending is the illusion of choice, because it can be made primarily with graphics and rely primarily on a text choice, a hidden item, etc. Using Metroid as an example, here's your generic winning scene. Samus takes off helmet and is a girl. Here's your losing cut scene (and if not by player failure, perhaps text choice TRY TO TAME SPACE RAPTORS? -->YES) Samus gets eaten by space raptors, "...and the galaxy was lost..." GAME OVER. Here's the gag ending where a player thinks they made a free will decision: you found the secret room with the cowboy hat that does nothing unless you wear it in the final boss fight, so roll cut scene of Samus putting cowboy hat on top of suit and using Ridley as a noble space steed on the way to more intergalactic world saving with Mr Poopy Butthole. Remember when that happened? That was awesome. But whatever the ending, it doesn't actually change what came before it, and everything the player does until the ending point is the same.

And then we need to figure out tone. We can make a really bittersweet ending even out of something wacky, like Link's Awakening. Or we can go the Mother/Earthbound route and prove that Freud was right all along. Or we can go Braid and play to the best heroic tropes and then make everything sad. Or @TheRagingRabbit can weigh in and save me from writing more paragraphs.

**Comment by evinstk** [comment]
> Or a scenario like my second idea, being contained to one large building, like a castle(vania) where a "wing" logically translates into any kind of map you want, really, including the one @adian91 proposed.

Pro tip! Reference an issue directly using the "#" symbol, as in issue #10.

**Comment by TheRagingRabbit** [comment]
Yeah, I’m going to agree that multiple unconnected world hits on the kingdom hearts problem. If we keep all the worlds isolated and unrelated within an overarching narrative, eventually all we want to do is play the overarching narrative.  

I have some comments about your stuff so far @RinTinRin. But first I would like to throw out a few more ideas.  

My first idea was a samurai hive mind in space. You would play an individual in that hivemind trying to reacquire several renegades who have not only left the hivemind, but are trying to destroy it. The twist here is that I want the hivemind to be the good guys. This is of course based on Rick and Morty’s “Unity” episode. It would be fun to explore the negative aspects of individualism: isolation, disproportionate coping mechanisms for different people, etc. It could be really fun. I think it would be neat to explore how the concepts of honor play into a hive mentality, and how a hivemind does not necessarily have to treat all of its parts (see people) like they are expendable drones.  

My second one is a post apocalypse scenario. This also includes a time travel mechanic. You are trying to piece together an apocalypse the day before it happens and three days later. We could have a few RPG elements in that in order to survive in the post-apocalypse you need to upgrade your suite to access certain areas. The actual reason for the apocalypse could be related to some villain, or it could be the main character’s fault. He could have some twisted motivation like in Josh Ritter’s “The Temptation of Adam,” and we the player watch him come to the decision to kill everyone. 

Here are my first comments on @RinTinRin

If we do duel character mode or a your time mechanic we solve two problems. The first is that we give our game a mechanic that relates the story directly to gameplay. The second is that we allow our artist and scripters to breath a bit. 

That is all I have for now. I will think more on your stuff as I work through tonight.

**Comment by RinTinRin** [comment]
Ooh, samurai hive mind sounds really fun. (Please let a character be named Watana-bee.) But I love it if only because it sounds like synopsis of Haruki Murakami writing a space opera. However, I worry that that might be a little too involved for a first project and better for a second project.

It sounds like blending some apocalypse ideas (and again, illusion of choice: let's just give players lots of heart wrenching endings) would be best. We both have some time travel, trying to avoid an awful future, and the potential for the main character to in fact be the villain rather than the hero by the end. Mine would have been more magic-y, but all my initial thoughts work just as well for harder scifi, and that short of a time gap is even easier to plan both for writing and for art design.

**Comment by RinTinRin** [comment]
And second comment because I can't edit my first on mobile (or don't know how to), seriously I would love to keep talking about the samurai hive mind idea with you--and in person soon. Just the time travel seems the better first try fit.

**Comment by evinstk** [comment]
Heads up: @GlasselRat has finished his task in issue #1. He will be stalled until he has an idea of what kind of setting we'll use. Please decide on a time and place first and inform Ryan of your decision.

Remember: This first game will be simple. The goal is to get it done quickly so that the team knows what it's doing. We can revisit some of the more advanced mechanics and storytelling in a future project.

**Comment by TheRagingRabbit** [comment]
@evinstk and @GlasselRat, @RinTinRin and I are going to work the universe in the evening. We will do it over Skype, and I will provide a full write up after we speak.

**Comment by evinstk** [comment]
Excellent! If the write-up is going to be in some sense official, instead of leaving it as a comment here, please write it in a new page on [our wiki](https://github.com/TheGovernorsJunk/MetroidClone/wiki). You can then link to the new page here and close the issue.

**Comment by GlasselRat** [comment]
Halfway through reading this whole thread, but Tanner check out the Penny Arcade on the Rainslick Precipice of Darkness episode 3.  There is a section where you are in a past and present version of a mansion simultaneously.  They did the art well.  @evinstk

**Comment by TheRagingRabbit** [comment]
At long last we, the writing team, have come up with a scenario. However, @evinstk , because I am taking the GRE tomorrow, I did not want to flesh out everything @RinTinRin and I came up with as far as the plot is concerned. One quick note: we elected not to do time travel for several reasons, but the main two were: we ended up nitpicking the whole thing to death and nothing we came up was very exciting.

Instead, we would like to propose a castle filled with furniture monsters, think Beauty and the Beast, that are magically sleeping as invulnerable stone. It is the players job to wake them up and kill them. However the player character has a special bell that will wake them for a limited time. We will go into that part of the scenario at a later time. The monsters would get progressively larger and more twisted as the player progressed. The goal is to slay all of the monsters. 

We propose a few final fantasy elements to the main character himself. He is the renowned greatest warrior in the world and carries a laser sword. He is looking for an ancestor that was put to sleep inside the castle. He and other NPCs don’t get permanently released from the stone sleep until the monsters are dead, however they can wake within the castle and interact with the player. Another character that we thought of was a psionic priest. I will leave it to @GlasselRat to decide what that should look like. 

This world would be like beauty and the beast meets the Dragon Riders of Pern. There is powerful, unbreakable technology left from a previous age. It is super valuable and rare, but could be incorporated into monsters, or even used as power ups. Rin suggested a grand laser piano. 

Ok, have fun. @RinTinRin and I will try to get a full scenario and plot outline written up this weekend.

**Comment by evinstk** [comment]
Great work, y'all. An original blend of a few inspirations&mdash;very nice. When either of you have the time, begin work on a write-up in a wiki page so we can have something more visible and semi-permanent. You can just copy and paste this comment as a placeholder for now.

@GlasselRat, we'll return to issue #7 and discuss specific requirements for your next spritesheet. (I still need to animate Nana; scripting is taking my priority right now.)

**Comment by GlasselRat** [comment]
![concept art 1 001](https://cloud.githubusercontent.com/assets/15863958/11314638/fc4d7270-8fac-11e5-8daf-fd89aba07696.jpg)

@TheGovernorsJunk/writers   I wanted to resist the temptation to make a lightsaber.  When I think future I picture stereotypical jumpsuits.  I chose opposite colors both so the design would stand out and because it looks nice.  By final fantasy standards the hair is pretty tame.  Also this is just concept art because it should be obvious that I drew the sword first and then had no idea what to do with his other arm, so he is holding a grenade.  And really the green part of the sword should be orange.

The outline is bolder than the other lines so that he will stand out more against a background

**Comment by evinstk** [comment]
Love these. Great job, Ryan.

**Comment by evinstk** [comment]
Let's consider this issue closed and direct any artwork related discussion to issue #7.
